name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (e.g. 1.0.0)
        type: string
        required: true
      notes:
        description: Release notes
        type: string
        required: false

jobs:
  release:
    # Run the release process on Windows runners to build native binaries.
    runs-on: windows-latest
    env:
      # Secrets must be provided via repository/environment settings once signing assets are available.
      WINDOWS_CERT_PFX_B64: ${{ secrets.WINDOWS_CERT_PFX }}
      WINDOWS_CERT_PASS: ${{ secrets.WINDOWS_CERT_PASS }}
      ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEY_PASS: ${{ secrets.ANDROID_KEY_PASS }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
    steps:
      - name: Checkout repository
        # Fetch full history so tags/releases can be created accurately.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET 8 SDK
        # Ensure the required .NET SDK and workloads are available.
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        # Install MAUI tooling needed for Android build targets.
        run: dotnet workload install maui --skip-manifest-update

      - name: Restore dependencies
        # Restore all solution dependencies before building.
        run: dotnet restore ShuffleTask.sln

      - name: Validate signing prerequisites
        # Fail fast with guidance if signing assets are not yet configured.
        shell: pwsh
        run: |
          if ([string]::IsNullOrWhiteSpace($env:WINDOWS_CERT_PFX_B64) -or [string]::IsNullOrWhiteSpace($env:WINDOWS_CERT_PASS)) {
            Write-Error "Windows signing secrets missing. Once you obtain your Authenticode .pfx file, base64-encode it and store it as WINDOWS_CERT_PFX, with the password in WINDOWS_CERT_PASS."
          }
          if ([string]::IsNullOrWhiteSpace($env:ANDROID_KEYSTORE_B64) -or [string]::IsNullOrWhiteSpace($env:ANDROID_KEY_PASS)) {
            Write-Error "Android signing secrets missing. After generating your keystore (.jks/.keystore), base64-encode it into ANDROID_KEYSTORE and place the password in ANDROID_KEY_PASS."
          }

      - name: Build Windows self-contained executable
        # Publish the Windows desktop application to the artifacts directory.
        run: >-
          dotnet publish ShuffleTask.Presentation/ShuffleTask.Presentation.csproj
          -c Release
          -r win-x64
          --self-contained true
          /p:PublishSingleFile=true
          -o ./artifacts/win

      - name: Build Android APK
        # Publish the Android application package via MAUI.
        run: >-
          dotnet publish ShuffleTask.Presentation/ShuffleTask.Presentation.csproj
          -c Release
          -f net8.0-android
          /p:AndroidPackageFormat=apk
          -o ./artifacts/android

      - name: Normalize artifact names
        # Ensure predictable artifact names for signing and release packaging.
        shell: pwsh
        run: |
          $winOutput = Get-ChildItem 'artifacts/win' -Filter *.exe | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $winOutput) { Write-Error 'Windows publish output missing expected .exe file.' }
          Rename-Item -Path $winOutput.FullName -NewName 'ShuffleTask.exe' -Force
          $apkOutput = Get-ChildItem 'artifacts/android' -Filter *.apk | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $apkOutput) { Write-Error 'Android publish output missing expected .apk file.' }
          Rename-Item -Path $apkOutput.FullName -NewName 'ShuffleTask.apk' -Force

      - name: Prepare Windows signing certificate
        # Decode the base64-encoded PFX certificate from environment secrets.
        shell: pwsh
        run: |
          $certPath = Join-Path $env:RUNNER_TEMP 'windows-signing-cert.pfx'
          [IO.File]::WriteAllBytes($certPath, [Convert]::FromBase64String($env:WINDOWS_CERT_PFX_B64))
          "WINDOWS_CERT_PATH=$certPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Prepare Android keystore
        # Decode the base64-encoded Android keystore from environment secrets.
        shell: pwsh
        run: |
          $keystorePath = Join-Path $env:RUNNER_TEMP 'android-signing-key.jks'
          [IO.File]::WriteAllBytes($keystorePath, [Convert]::FromBase64String($env:ANDROID_KEYSTORE_B64))
          "ANDROID_KEYSTORE_PATH=$keystorePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Sign Windows executable
        # Apply Authenticode signature to the Windows binary.
        run: >-
          signtool sign
          /f "$env:WINDOWS_CERT_PATH"
          /p "$env:WINDOWS_CERT_PASS"
          /tr http://timestamp.digicert.com
          /td sha256
          /fd sha256
          artifacts\win\ShuffleTask.exe

      - name: Sign Android APK
        # Sign the Android package with jarsigner.
        shell: pwsh
        run: |
          $apkPath = Resolve-Path 'artifacts/android/ShuffleTask.apk'
          $alias = if ($env:ANDROID_KEY_ALIAS) { $env:ANDROID_KEY_ALIAS } else { 'android' }
          $storePassFile = Join-Path $env:RUNNER_TEMP 'storepass.txt'
          Set-Content -Path $storePassFile -Value $env:ANDROID_KEY_PASS -NoNewline
          jarsigner -keystore "$env:ANDROID_KEYSTORE_PATH" -storepass:file "$storePassFile" -keypass:file "$storePassFile" "$apkPath" $alias
          Remove-Item $storePassFile -Force

      - name: Create GitHub Release
        # Publish the signed artifacts as a GitHub Release.
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.notes }}
          files: |
            artifacts/win/ShuffleTask.exe
            artifacts/android/ShuffleTask.apk
