name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version to release (e.g., 1.0.0)'
        type: string
        required: true
      notes:
        description: 'Release notes (optional)'
        type: string
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ github.event.inputs.version }}
      release-status: ${{ steps.release-status.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate version input
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [ -z "$VERSION" ]; then
            echo "✗ Version is required. Please provide a semantic version (e.g., 1.0.0)"
            exit 1
          fi
          echo "Processing version: $VERSION"

      - name: Check if release already exists
        id: check-release
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "Checking for existing release for version: $VERSION"

          if gh release view "$VERSION" &>/dev/null; then
            echo "✓ Release already exists for version $VERSION"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No existing release found"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if signed artifacts exist
        if: steps.check-release.outputs.exists == 'false'
        id: check-signed
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.SHUFFLE_TASK_ARTIFACT_ACCESS_EXPIRES_03OCT2026 }}
        run: |
          $repo = "${{ github.repository }}"
          $version = "${{ github.event.inputs.version }}"
          $expected = @(
            "signed-$version-windows",
            "signed-$version-android",
            "signed-$version-metadata"
          )

          $response = gh api "repos/$repo/actions/artifacts?per_page=100" | ConvertFrom-Json
          $artifacts = @()
          if ($null -ne $response.artifacts) { $artifacts = $response.artifacts }

          $windowsArtifact = $artifacts | Where-Object { $_.name -eq $expected[0] -and $_.expired -eq $false } | Select-Object -First 1
          $androidArtifact = $artifacts | Where-Object { $_.name -eq $expected[1] -and $_.expired -eq $false } | Select-Object -First 1
          $metadataArtifact = $artifacts | Where-Object { $_.name -eq $expected[2] -and $_.expired -eq $false } | Select-Object -First 1

          if (-not $windowsArtifact -or -not $androidArtifact -or -not $metadataArtifact) {
            Write-Host "✗ Signed artifacts not found for version $version"
            Write-Host "Ensure the Sign Artifacts workflow has been completed for this version."
            throw "Signed artifacts missing."
          }

          echo "windows_url=$($windowsArtifact.archive_download_url)" >> $env:GITHUB_OUTPUT
          echo "android_url=$($androidArtifact.archive_download_url)" >> $env:GITHUB_OUTPUT
          echo "metadata_url=$($metadataArtifact.archive_download_url)" >> $env:GITHUB_OUTPUT

          Write-Host "✓ Signed artifacts found for version $version"

      - name: Download signed artifacts
        if: steps.check-release.outputs.exists == 'false'
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.SHUFFLE_TASK_ARTIFACT_ACCESS_EXPIRES_03OCT2026 }}
        run: |
          $version = "${{ github.event.inputs.version }}"

          $downloadRoot = Join-Path (Get-Location) 'release-downloads'
          if (Test-Path $downloadRoot) { Remove-Item $downloadRoot -Recurse -Force }
          New-Item -ItemType Directory -Force -Path $downloadRoot | Out-Null

          $winZip = Join-Path $downloadRoot 'signed-windows.zip'
          $androidZip = Join-Path $downloadRoot 'signed-android.zip'
          $metadataZip = Join-Path $downloadRoot 'signed-metadata.zip'

          $headers = @{ 'Authorization' = "Bearer $env:GH_TOKEN"; 'Accept' = 'application/octet-stream' }

          Invoke-WebRequest -Uri "${{ steps.check-signed.outputs.windows_url }}" -Headers $headers -OutFile $winZip
          Invoke-WebRequest -Uri "${{ steps.check-signed.outputs.android_url }}" -Headers $headers -OutFile $androidZip
          Invoke-WebRequest -Uri "${{ steps.check-signed.outputs.metadata_url }}" -Headers $headers -OutFile $metadataZip

          $winExtract = Join-Path $downloadRoot 'windows'
          $androidExtract = Join-Path $downloadRoot 'android'
          $metadataExtract = Join-Path $downloadRoot 'metadata'
          New-Item -ItemType Directory -Force -Path $winExtract | Out-Null
          New-Item -ItemType Directory -Force -Path $androidExtract | Out-Null
          New-Item -ItemType Directory -Force -Path $metadataExtract | Out-Null

          Expand-Archive -Path $winZip -DestinationPath $winExtract -Force
          Expand-Archive -Path $androidZip -DestinationPath $androidExtract -Force
          Expand-Archive -Path $metadataZip -DestinationPath $metadataExtract -Force

          $releaseRoot = Join-Path (Get-Location) 'release-artifacts'
          if (Test-Path $releaseRoot) { Remove-Item $releaseRoot -Recurse -Force }
          New-Item -ItemType Directory -Force -Path $releaseRoot | Out-Null

          $windowsTarget = Join-Path $releaseRoot 'windows'
          $androidTarget = Join-Path $releaseRoot 'android'
          New-Item -ItemType Directory -Force -Path $windowsTarget | Out-Null
          New-Item -ItemType Directory -Force -Path $androidTarget | Out-Null

          $windowsSource = Join-Path (Join-Path $winExtract 'artifacts') 'win'
          $androidSource = Join-Path (Join-Path $androidExtract 'artifacts') 'android'
          $metadataSource = Join-Path (Join-Path $metadataExtract 'artifacts') 'VERSION.txt'

          if (-not (Test-Path $windowsSource)) { throw "Signed Windows files not found at $windowsSource" }
          if (-not (Test-Path $androidSource)) { throw "Signed Android files not found at $androidSource" }
          if (-not (Test-Path $metadataSource)) { throw "VERSION.txt not found at $metadataSource" }

          Copy-Item -Path (Join-Path $windowsSource '*') -Destination $windowsTarget -Recurse -Force
          Copy-Item -Path (Join-Path $androidSource '*') -Destination $androidTarget -Recurse -Force
          Copy-Item -Path $metadataSource -Destination (Join-Path $releaseRoot 'VERSION.txt') -Force

          Remove-Item $winZip, $androidZip, $metadataZip -Force
          Remove-Item $downloadRoot -Recurse -Force

          Get-ChildItem -Path ./release-artifacts -Recurse

      - name: Prepare packaged assets
        if: steps.check-release.outputs.exists == 'false'
        shell: pwsh
        run: |
          $version = "${{ github.event.inputs.version }}"
          $releaseRoot = Join-Path (Get-Location) 'release-artifacts'
          $windowsDir = Join-Path $releaseRoot 'windows'
          $androidDir = Join-Path $releaseRoot 'android'
          $versionFile = Join-Path $releaseRoot 'VERSION.txt'

          if (-not (Test-Path $windowsDir)) { throw "Windows payload directory missing at $windowsDir" }
          if (-not (Test-Path $androidDir)) { throw "Android payload directory missing at $androidDir" }
          if (-not (Test-Path $versionFile)) { throw "VERSION.txt missing at $versionFile" }

          $winExe = Get-ChildItem $windowsDir -Filter *.exe -Recurse | Where-Object { $_.Name -like 'ShuffleTask*.exe' } | Select-Object -First 1
          if (-not $winExe) { $winExe = Get-ChildItem $windowsDir -Filter *.exe -Recurse | Select-Object -First 1 }
          if (-not $winExe) { throw "No Windows executable found under $windowsDir" }

          $winZip = Join-Path $releaseRoot "ShuffleTask-$version-windows.zip"
          if (Test-Path $winZip) { Remove-Item $winZip -Force }
          Compress-Archive -Path (Join-Path $windowsDir '*') -DestinationPath $winZip -Force

          $apkFile = Get-ChildItem $androidDir -Filter *.apk -Recurse | Select-Object -First 1
          if (-not $apkFile) { throw "No Android APK found under $androidDir" }

          $apkTarget = Join-Path $releaseRoot "ShuffleTask-$version.apk"
          Copy-Item $apkFile.FullName $apkTarget -Force

          Write-Host "Prepared packaged assets:"
          Write-Host "  Windows ZIP: $([System.IO.Path]::GetRelativePath((Get-Location).Path, $winZip))"
          Write-Host "  Android APK: $([System.IO.Path]::GetRelativePath((Get-Location).Path, $apkTarget))"
          Write-Host "  VERSION.txt: $([System.IO.Path]::GetRelativePath((Get-Location).Path, $versionFile))"

      - name: Create release notes
        if: steps.check-release.outputs.exists == 'false'
        id: release-notes
        run: |
          VERSION="${{ github.event.inputs.version }}"
          USER_NOTES="${{ github.event.inputs.notes }}"

          cat > release-notes.md << EOF
          # ShuffleTask v$VERSION

          $USER_NOTES

          ## Installation

          ### Windows
          Download \`ShuffleTask-$VERSION-windows.zip\`, extract the contents, and run \`ShuffleTask-$VERSION.exe\` from the unpacked folder.

          ### Android
          Download \`ShuffleTask-$VERSION.apk\` and install it on your Android device. You may need to enable "Install from unknown sources" in your device settings.

          ## What's Changed

          See the [full changelog](https://github.com/yaron-E92/ShuffleTask/compare/v$VERSION...main) for details.

          ---

          *Built on $(date -u '+%Y-%m-%d %H:%M:%S UTC')*
          EOF

          echo "Release notes created"

      - name: Create GitHub Release
        if: steps.check-release.outputs.exists == 'false'
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "Creating GitHub release for version: $VERSION"

          gh release create "$VERSION" \
            --title "ShuffleTask v$VERSION" \
            --notes-file release-notes.md \
            ./release-artifacts/ShuffleTask-$VERSION-windows.zip \
            ./release-artifacts/ShuffleTask-$VERSION.apk \
            ./release-artifacts/VERSION.txt

          echo "✓ Release created successfully"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mark release status
        id: release-status
        if: always()
        run: |
          if [ "${{ job.status }}" != "success" ]; then
            echo "status=failed" >> $GITHUB_OUTPUT
          elif [ "${{ steps.check-release.outputs.exists }}" = "true" ]; then
            echo "status=skipped" >> $GITHUB_OUTPUT
          else
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: Skip message
        if: steps.check-release.outputs.exists == 'true'
        run: |
          echo "================================================"
          echo "Release already exists for version ${{ github.event.inputs.version }}"
          echo "Skipping release creation."
          echo "To create a new release, use a different version number."
          echo "================================================"

  summary:
    runs-on: ubuntu-latest
    needs: release
    if: always()
    steps:
      - name: Release summary
        run: |
          echo "## Release Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ needs.release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ needs.release.outputs.release-status }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ needs.release.outputs.release-status }}" == "success" ]; then
            echo "✓ Release created successfully." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Release URL:** https://github.com/yaron-E92/ShuffleTask/releases/tag/${{ needs.release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The release is now public and available for download." >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.release.outputs.release-status }}" == "skipped" ]; then
            echo "✓ Release already exists for this version." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Release URL:** https://github.com/yaron-E92/ShuffleTask/releases/tag/${{ needs.release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "✗ Release failed or status unknown." >> $GITHUB_STEP_SUMMARY
          fi
